<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>AQUI SE PRUEBAN TODOS LOS CASOS DE PRUEBA DEL MODULO RECEPCION.</description>
   <name>RECEPCION</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>1c99480e-fa29-4068-82d9-ad968f560e2e</testSuiteGuid>
   <testCaseLink>
      <guid>8613b465-3ee6-4ccd-841a-25db62d80cd0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Micoparainmuno/MSP-10-371</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60f4c1aa-aabd-44e4-94e4-46c2db316b48</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d001ae1-70ca-435e-ac27-b37ec5e72851</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a85697bf-c6e6-4a49-b3d7-652cbea0237c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d031f50-dc31-467d-b7ad-bf2cc0ef3c4b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8ca2e87-4d3b-4103-9a75-307e3cd4cfaf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf3822c6-537e-486a-a014-a68c65d054cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e6cffe4-d54a-4bcc-9934-ac3e1e159d4c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b990d3b6-05c2-496f-bf87-b4eae907a2a5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8602446-d2d2-4c5f-b1fe-82eb4e1dbb01</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8a10720-c8f9-4ebc-bd0b-08dc25cd277a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c2b54c3-0b8e-4276-8802-a0a34dcc37e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ef9cf65-f4b4-4362-9290-cbbd377aaa04</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ae03658-f0e5-4547-9dfc-cd15da060d07</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e39041bd-f26d-408a-9f85-92c7bccc0336</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a829526e-8094-49a4-a9a7-6e197358b00d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8b129c9-47f9-4df9-abd0-9abf5b09b635</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>573db809-53a1-4ef2-af98-fa757f779170</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Micoparainmuno/MSP-11-372</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec1ae3b3-398d-4962-9c5f-f4741feb59ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6045f61-283c-47d6-9c59-05941bb05bf6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c926263-1198-4d77-a497-642727869fcf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6febdf8f-708b-4a51-a90d-809da1937fbe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a4fa29d-1b60-4e95-a6f7-cf3317818711</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06d49018-c1b2-4a6e-8203-ca6d25d281d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>871789a7-2864-474e-b339-d0da554ada8c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1033e38-acd9-4a4d-9d51-ebac87f74b20</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a69385e-b597-42a9-b682-f2637c76f62c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4fa3b37b-7a73-4735-b693-021f296d762e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4acef437-8b43-4af6-ad90-d558849e5f00</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b40efd50-936a-43a5-8d84-74816346c9bb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a77d6fc3-d2ca-4c9e-9b1d-561a35918b79</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8f86476-ab76-4dec-9b67-ca2aa7c401ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54550c77-5835-4800-b516-5cd07d354d0d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e430b4b6-e9ab-4920-ace3-20b59f070a91</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5e29777a-bd12-48bd-9d56-4a99b32cafd5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud/MSP-22</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f47dfcbe-7f8f-4a6d-bda4-d83222046155</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fcbd7b66-00d9-4110-91ca-b36ac62b2f19</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud/MSP-24</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6cc02b20-3850-49dd-8ac6-30efbca5c0aa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0ac8dd1f-a55d-407b-a30f-59a50039d1f1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_Cepas/MSP-2</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cac90cca-76bc-4a1b-8aee-a459ec545f45</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3afa9f12-3b85-4402-89ed-78a71239776e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>83bea7e3-acf0-47e7-af27-db54cdb9692b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_Cepas/MSP-3</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9954dfaa-56c1-4947-9a95-93998ccdf08d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd493282-f0b3-482f-aab7-9db2f68809a4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6f9c5edb-67fe-40a5-847a-ba5adc099939</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_Coprocultivo/MSP-26</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d490957-dcac-4ca8-bfea-11f8a34b8024</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e5bacc9-0b38-4afc-9adb-262e207701ef</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6a803de9-7ef7-4f81-8493-fef0a8afe80d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_Coprocultivo/MSP-27</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74b9d3c4-43b5-46fc-8880-e13c85b27127</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d0d3dbd-83cf-49ee-8cf3-40cc3f7249f4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>48c340f6-ae6b-4c0a-a699-72a7b172b351</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_Micoparafung/MSP-6</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07d5b312-1b5a-46e9-9918-541bbf991184</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>16d4f548-502b-4ef7-b3fa-a5207014aab3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_Micoparafung/MSP-7</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>798f10b3-aede-4b6a-aa04-0b200c268892</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>723bc19e-fead-4e7b-b448-d04ef2853f5e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_Moleculares/MSP-14</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0de0c9db-2e19-4e5c-a841-c84599411fa0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8498ba2-e636-49cf-af59-15e49d7844bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>917c9739-9cbd-4ef4-9dc1-5e23d74d2b08</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e28644a0-8b04-4a86-9d6c-8332aca6cf6f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4702338-c2c8-4d9d-8ea6-59e237cef4d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09708569-ca54-46ef-9e88-6429dbe9ce65</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fd9412ce-eb43-4bec-b770-28ea7854908e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_Moleculares/MSP-15</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cce2eb03-e63e-4d40-acce-a8f5d9cfc39f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>071eaafb-330d-4f32-a82d-9ca45537fda5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab40f432-155d-44af-91f3-8fdb68675a44</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22ff709e-2400-4633-a5b5-48c6a1152049</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>abb7fc15-9348-4d5b-8db3-dfb30059eece</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>662cb225-2fe1-40db-b79a-a6279e51852b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6a7a3130-c00e-4345-a069-f095715d4ce8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_Tosconvulsa/MSP-18</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e76f0b1-2365-4296-a44d-5c4c223c715e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>005a4ca4-ac15-4135-8b75-49959d8b20a7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_Tosconvulsa/MSP-20</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a0db817-b494-4ccd-ac21-85ec4f6ebdbc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eb75ee0c-62ce-48b3-8af2-25723e836281</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMayoresVirologia120/MSP-378</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>96e21b9b-5457-46a6-aa92-905776de73a5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMayoresVirologia120/MSP-379</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>9438784e-72c5-47e5-b033-b0bc89bbf385</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMayoresVirologia120/MSP-380</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>8f794c25-6236-410f-8f16-919f36b82a06</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMayoresVirologia120/MSP-382</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>1ed5cd03-5382-4f40-876d-c18e59970253</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMayoresVirologia120/MSP-383</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>73c88c20-c735-477c-b465-f90ab5217eb0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMayoresVirologia120/MSP-384</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>be5dad30-a13e-446a-989b-d89f1b643116</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMayoresVirologia120/MSP-385</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>56a243f1-e9ed-4f28-b15e-ce19e7dc157a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMayoresVirologia120/MSP-386</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>fc0748c0-5e5c-45ea-9eed-ba3048658bcb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMayoresVirologia120/MSP-387</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>ae037ccf-bdf7-4395-99e8-578294c448c3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMayoresVirologia120/MSP-388</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>0e6c5b12-0de4-4326-804f-ae0af774919c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMayoresVirologia120/MSP-389</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>18f0ddbd-a6b9-4c90-bea2-b8ababc0ac42</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMayoresVirologia120/MSP-390</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>dfd49acc-1f4d-42fc-b201-286634a08861</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMayoresVirologia120/MSP-391</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>5900c384-3856-41a0-b26a-e08bef0b43dd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMayoresVirologia120/MSP-392</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>b2ea503e-e5e6-429e-8ea1-e696df11b75b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMayoresVirologia120/MSP-393</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>2ea0c8b4-ab10-4535-b622-8fcd8caebfd2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMayoresVirologia120/MSP-394</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>9385ddb3-5d31-4b5a-868b-ddc942f069e0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMayoresVirologia120/MSP-395</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>9432f55c-c286-47df-a2f5-e6fda16868c1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMayoresVirologia120/MSP-396</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>2cb4b7aa-2b34-4668-b93d-02cacae2f47c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMayoresVirologia120/MSP-397</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>03d6d841-127f-418f-b6f5-1ff1eb7bdfd7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMayoresVirologia120/MSP-398</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>6e9fb553-616e-4a16-a372-22ebb519a704</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMayoresVirologia120/MSP-399</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>68a687dc-add9-4cff-9e29-5f2e15e524ee</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMayoresVirologia120/MSP-400</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>21dd76bc-074a-45c9-bcd9-a7265379bcf4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMayoresVirologia120/MSP-401</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>4c38b4ba-d66e-4798-a4a2-3dc8310a8e48</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMayoresVirologia120/MSP-402</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>8fa50fd0-fca5-45a8-a680-96a81ec0ab6b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMayoresVirologia120/MSP-403</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>1fc990bd-3af4-446b-a252-60fb3392611b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMayoresVirologia120/MSP-404</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>95be27f7-ef23-4102-ba32-5a851e824cd2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMayoresVirologia120/MSP-405</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>5d6dc0f6-4e63-43fc-815f-655bf22c7f28</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMayoresVirologia120/MSP-406</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>260d2b14-448a-4058-ad8b-371d96b578cd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMayoresVirologia120/MSP-407</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>9dff4fd3-659f-4cdd-8478-ce6834c6f5f1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMayoresVirologia120/MSP-408</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>083f10b1-f2c7-4b41-863e-bfaeb9a189fb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMayoresVirologia120/MSP-409</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>f4e5966e-b66b-43d5-b434-3eb69c61fc3b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMayoresVirologia120/MSP-410</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>af4e21de-d9bc-4893-983b-c9c49c25c8ae</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMayoresVirologia120/MSP-411</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>871f6b87-b599-4daa-b97a-a1bca25c914b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMayoresVirologia120/MSP-412</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>c49616f5-36e6-41f1-8745-32e861a577a1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMayoresVirologia120/MSP-413</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>4588ebf5-a415-41d8-b2f2-73d2538d4903</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMayoresVirologia120/MSP-414</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>65d3b113-22b2-4153-b4b5-0cc3aa6a1f5e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMayoresVirologia120/MSP-416</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>ba37dad0-fe30-4f06-80ab-fa421cbbb108</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMayoresVirologia120/MSP-417</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>21a70dce-ae54-4b96-a1c5-8366b7690a48</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMayoresVirologia120/MSP-418</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>565045f6-195f-42a2-9256-970595bcfef8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMenoresVirologia121/MSP-373</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>8ec9befa-71b4-42cd-976d-1a041f854f4c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMenoresVirologia121/MSP-374</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>181b5bbb-ec81-41e5-8c09-94947547030b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMenoresVirologia121/MSP-377</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>cdc03a07-c2ae-455b-bfbe-a3cc820324ed</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Recepcion/Formulario_Solicitud_VIHMenoresVirologia121/MSP-381</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
