<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_PAIS</name>
   <tag></tag>
   <elementGuidId>07b7b6c8-b752-40b5-b4eb-9dd14a2084b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='SOL_EXTRANJEROPAISID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SOL_EXTRANJEROPAISID</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SOL_EXTRANJEROPAISID</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 239,'',false,'',0)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>gx.evt.onchange(this, event)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>;gx.evt.onblur(this,239);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoch0</name>
      <type>Main</type>
      <value>if(!(gx.evt.jsEvent(this))) return false;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoldvalue</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxvalid</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
(Ninguno)AFGANISTÁNALBANIAALEMANIAALGERIAANDORRAANGOLAANGUILLAANTIGUA Y BARBUDAARABIA SAUDITAARGENTINAARMENIAARUBAAUSTRALIAAUSTRIAAZERBAIYÁNBAHAMASBAHREINBANGLADESHBELICEBENINBERMUDABHUTÁNBIELORRUSIABOLIVIABOSNIA HERZEGOVINABOTSWANABRASILBRUNEI DARUSSALAMBULGARIABURKINA FASOBURUNDIBÉLGICACABO VERDECAMBOYACAMERÚNCANADÁCHADCHILECHINACHIPRECOLOMBIACOMORASCONGOCOOK ISLANDSCOSTA DE MARFILCOSTA RICACROACIACUBADINAMARCADJIBOUTÍDOMINICAECUADOREEUUEGIPTOEL SALVADOREMIRATOS ARABES UNIDOSERITREAESLOVAQUIAESLOVENIAESPAÑAESTONIAETIOPÍAFALKLAND ISLANDS (MALVINAS)FAROE ISLANDSFIDJIFILIPINASFINLANDIAFRANCIAFRENCH GUIANAFRENCH POLYNESIAGABÓNGAMBIAGEORGIAGHANAGIBRALTARGRANADAGRECIAGREENLANDGUADELOUPEGUAMGUATEMALAGUINEAGUINEA ECUATORIALGUINEA-BISSAUGUYANAHAITÍHOLANDAHOLY SEE (VATICAN CITY STATE)HONDURASHONG KONGHUNGRÍAINDIAINDONESIAIRAQIRLANDAIRÁNISLANDIAISLAS CAIMÁNISLAS MARSHALLISLAS MAURICIOISLAS SALOMÓNISRAELITALIAJAMAICAJAPÓNJORDANIAKAZAKJSTÁNKENYAKIRGUISTÁNKIRIBATÍKUWAITLAOSLESOTHOLETONIALIBERIALIBIALIECHTENSTEINLITUANIALUXEMBURGOLÍBANOMACAOMADAGASCARMALASIAMALAWIMALDIVASMALTAMALÍMARRUECOSMARTINIQUEMAURITANIAMICRONESIAMOLDOVAMONGOLIAMONTSERRATMOZAMBIQUEMYANMARMÉXICOMÓNACONAMIBIANAURUNEPALNETHERLANDS ANTILLESNEW CALEDONIANICARAGUANIGERIANIUENORFOLK ISLANDNORTHERN MARIANA ISLANDSNORUEGANUEVA ZELANDIANÍGEROMÁNPAKISTÁNPALAUPANAMPAPÚA NUEVA GUINEAPARAGUAYPERÚPITCAIRNPOLONIAPORTUGALPUERTO RICOQATARREINO UNIDOREPÚBLICA CENTRAFRICANAREPÚBLICA CHECAREPÚBLICA DE COREAREPÚBLICA DEMOCRÁTICA DEL CONGOREPÚBLICA DOMINICANAREPÚBLICA POPULAR DE COREAREPÚBLICA YUGOSLAVA DE MACEDONIAREUNIONRUMANIARUSIARWANDASAINT HELENASAINT PIERRE AND MIQUELONSAMOASAMOA AMERICANASAN CRISTÓBAL Y NEVISSAN MARINOSAN VICENTE Y LAS GRANADINASSANTA LUCÍASANTO TOMÉ Y PRÍNCIPESENEGALSEYCHELLESSIERRA LAONASINGAPURSOMALIASRI LANKASUDÁFRICASUDÁNSUECIASUIZASURINAMSVALBARD AND JAN MAYENSWAZILANDIASYRIAN ARAB REPUBLICTAILANDIATAIWAN, PROVINCE OF CHINATANZANIATAYIKISTÁNTOGOTOKELAUTONGATRINIDAD Y TABAGOTURKMENISTÁNTURKS AND CAICOS ISLANDSTURQUÍATUVALÚTÚNEZUCRANIAUGANDAURUGUAYUZBEKISTÁNVANUATÚVENEZUELAVIETNAMVIRGIN ISLANDS, BRITISHVIRGIN ISLANDS, U.S.WALLIS AND FUTUNAWESTERN SAHARAYEMÉNZAMBIAZIMBABWE</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SOL_EXTRANJEROPAISID&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='SOL_EXTRANJEROPAISID']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='TABLEDATOSINFECCION']/tbody/tr[2]/td[4]/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='País'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vía más probable de adquisición de VIH:'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vía Sexual:'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/select</value>
   </webElementXpaths>
</WebElementEntity>
