<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(Todos)Organizacion</name>
   <tag></tag>
   <elementGuidId>b45852fd-d9a1-4c00-9078-a17cba53ce3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='vSOL_ORGANIZACIONID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vSOL_ORGANIZACIONID</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vSOL_ORGANIZACIONID</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 111,'',false,'0001',0)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>gx.evt.onchange(this, event)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>;gx.evt.onblur(this,111);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gxoch0</name>
      <type>Main</type>
      <value>if(!(gx.evt.jsEvent(this))) return false;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
(Todos)AIGUA CTRO AUXAMEDRINANCAPARTIGAS CTRO DPTALASOCIACION ESPAÑOLA PRIMERA DE MUTUO SOCORROASOCIACION MEDICA DE SAN JOSEBANCO DE PREVISION SOCIALBANCO DE SANGREBANCO DE SEGUROS DEL ESTADOBATLLE Y ORDOÑEZ CTRO AUXBAYERBELLA UNION CTRO AUXBIODIAGNOSTICO - CABINSUR S.ABIOERIXBIOFASTBIOTECBLUE CROSSCAMCELCAMDELCAMECCAMEDURCAMEPACAMOCCAMSCAMY (COOPERATIVA ASISTENCIA MEDICA YOUNG)CANELONES CTRO DPTALCANELONES DEPTAL DE SALUDCAP 2 - BATALLON DE INFANTERIA Nº2CARDONA CTRO AUXCARMELO CTRO AUXCASA DE GALICIACASMERCASMUCASTILLOS CTRO AUXCELSIUSCENTRO CLAVEAUX-LAPSCENTRO DE MEDICINA Y ESPECIALIDADESCENTRO DE SALUD CIUDAD DE LA COSTACENTRO DEPARTAMENTAL SAN JOSECENTRO MEDICO SALTOCENTRO NACIONAL DE QUEMADOS (CENAQUE)CERRO CHATO CTRO AUXCERRO LARGO CTRO DPTALCHUY CENTRO AUXCIRCULO CATOLICOCLINICA URGENTERAPCLÍNICA PREVENTIVACOLONIA CTRO DPTALCOLONIA ETCHEPARECOLONIA SANTIN CARLOS ROSSICOMEFCOMEFLOCOMEPACOMERI (COOP. MEDICA RIVERA)COMEROCOMTACOOPERATIVA MEDICA DE CANELONES COMECACOOPERATIVA MEDICA DE TREINTA Y TRESCOOPERTIVA MEDICA DE FLORESCOPAMHICOSEMCRAMICUDAMDERMAGROUP SRLDEVISA- DPTO DE VIGILANCIA EN SALUDDIRECCION DPTAL DE SALUD TREINTA Y TRESDLSPDOLORES CTRO AUXDURAZNO CTRO DPTALEBROMARFAMINTER S.AFARMATEC URUGUAY S.AFLORES CTRO DPTALFLORIDA CTRO DPTALFUERZA AEREA URUGUAYAGRAMON BAGOGREGORIO DE POLANCO CTRO AUXGREMCAGREMEDAGUICHON CTRO AUXHEMOCENTRO MALDONADOHONIMELL-WINPHARMHOSPITAL BRITANICOHOSPITAL CENTRAL DE LAS FFAAHOSPITAL DE CLINICASHOSPITAL DE FRAY BENTOSHOSPITAL DE MINASHOSPITAL DE SAN JOSEHOSPITAL DE TACUAREMBOHOSPITAL ESCUELA DEL LITORALHOSPITAL ESPAÑOLHOSPITAL EVANGELICOHOSPITAL MACIELHOSPITAL PASTEURHOSPITAL PEREIRA ROSSELLHOSPITAL PIÑEIRO DEL CAMPOHOSPITAL POLICIALHOSPITAL SAINT BOISHOSPITAL VILARDEBOI.N.A.UIAC INSTITUCION ASISTENCIAL COLECTIVAINAUINST NACIONAL DE TRANSPLANTEINSTITUTO DE CARDIOLOGIA INFANTILINSTITUTO DE ONCOLOGIAINSTITUTO NACIONAL DE ORTOPEDIA Y TRAUMATOLOGIAINSTITUTO NACIONAL DE REUMATOLOGIAINSTITUTO TECNICO FORENSEIZASA URUGUAY S.AJOHNSON &amp; JOHNSON DE URUGUAY S.AJUAN LACAZE CTRO AUXJUZGADO PENAL  MENORES CHUYLAB IVD URUGUAY S.A -WIENERLABORATORIO ALFALABORATORIO ARTIGASLABORATORIO BIANCHILABORATORIO BIOESTELABORATORIO C.D.PLABORATORIO C.E.BLABORATORIO CAJALLABORATORIO CASTRO GHERARDILABORATORIO CEB (CENTRO DE ESTUDIOS BIOQUÍMICOS)LABORATORIO CEPREDILABORATORIO DE ANALISIS CLINICOS RICARDO DIEZLABORATORIO DE ESTUDIOS PARACLINICOSLABORATORIO FARMACO URUGUAYOLABORATORIO FERTILABLABORATORIO GADORLABORATORIO HYGEALABORATORIO LAS PIEDRASLABORATORIO LIBRALABORATORIO MALDONADOLABORATORIO MARTINEZ PRADOLABORATORIO MONTEVERDELABORATORIO MONTEVIDEOLABORATORIO RIVERALABORATORIO ROIGLABORATORIO SALTOLABORATORIO SIEMBRASURLABORATORIO TEIXEIRALABORATORIO U.C.MLABORATORIO VIERA DE BRITOSLABORATORIOS CLAUSEN S.ALABORATORIOS PELLIERLABORATORIOS UNIDOSLABORATOROS PELLIER SRLLAS PIEDRAS CTRO AUXLASCANO CTRO AUXLAVALLEJA CTRO DPTALLIBERTAD CTRO AUXMALDONADO CTRO DPTALMEDICA URUGUAYAMEDICAREMEDICINA PERSONALIZADAMEFRE SRLMINAS DE CORRALES CTRO AUXMSPNEPHROS. CENTRO DE DIALISISNUEVA HELVECIA CTRO AUXNUEVA PALMIRA CTRO AUXORAMECOPAN DE AZUCAR CTRO AUXPANDO CTRO AUXPASO DE LOS TOROS CTRO AUXPAYSANDU CTRO DPTALPRUEBA ORGRINQUE PHARMARIO BRANCO CTRO AUXRIO NEGRO CTRO DPTALRIVERA CTRO DPTALROCHA CTRO DPTALROCHEROSARIO CTRO AUXSALTO CTRO DPTALSAN CARLOS CTRO AUXSAN JOSE CTRO DPTALSAN RAMON CTRO AUXSANATORIO AMERICANOSANATORIO CANTEGRILLSANATORIO MAUTONESANTA LUCIA CTRO AUXSAPP S.A (EMERGENCIA MOVIL PQUE DEL PLATA)SARANDI DEL YI CTRO AUXSARANDI GRANDE CTRO AUXSERVICIO ENF INFECTOCONTAGIOSASSIEMENS S.ASMISORIANO CTRO DPTALSUATSWISS MEDICAL URUGUAYTACUAREMBO CTRO DPTALTALA CTRO AUXTREINTA Y TRES CTRO DPTALTRESULUNIVERSALVERGARA CTRO AUXVISUR LTDAYOUNG CTRO AUXYTUYKJZIGEL LTDA NOVAMEDICAL</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vSOL_ORGANIZACIONID&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='vSOL_ORGANIZACIONID']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='TABLE2']/tbody/tr[4]/td[6]/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organización:'])[2]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estudio:'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paciente:'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingreso por DLSP:'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[6]/select</value>
   </webElementXpaths>
</WebElementEntity>
